// generated by stringer -type=Scope; DO NOT EDIT

package parser

import "fmt"

const _Scope_name = "OUTSCOPEDIN_COMMENTIN_ML_COMMENTREADING_COMMANDREADING_ARGUMENTSREADING_NUMBERREADING_WORDREADING_STRING"

var _Scope_index = [...]uint8{0, 9, 19, 32, 47, 64, 78, 90, 104}

func (i Scope) String() string {
	if i < 0 || i >= Scope(len(_Scope_index)-1) {
		return fmt.Sprintf("Scope(%d)", i)
	}
	return _Scope_name[_Scope_index[i]:_Scope_index[i+1]]
}
