// generated by stringer -type=scope; DO NOT EDIT

package parser

import "fmt"

const _scope_name = "OUTSCOPEDIN_COMMENTREADING_COMMANDREADING_ARGUMENTSREADING_NUMBERREADING_WORDREADING_STRING"

var _scope_index = [...]uint8{0, 9, 19, 34, 51, 65, 77, 91}

func (i scope) String() string {
	if i < 0 || i >= scope(len(_scope_index)-1) {
		return fmt.Sprintf("scope(%d)", i)
	}
	return _scope_name[_scope_index[i]:_scope_index[i+1]]
}
